const axios = require("axios")

const GITHUB_TOKEN = process.env.GITHUB_TOKEN
const OWNER = process.env.GITHUB_OWNER
const REPO = process.env.GITHUB_REPO

async function getIssue(issueNumber) {
    try {
        const res = await axios.get(
            `https://api.github.com/repos/${OWNER}/${REPO}/issues/${issueNumber}`,
            {
                headers: {
                    Authorization: `Bearer ${GITHUB_TOKEN}`,
                    Accept: "application/vnd.github+json"
                }
            }
        )

        return res.data
    } catch (err) {
        if (err.response && err.response.status === 404) {
            throw new Error(`Issue #${issueNumber} not found`)
        }
        throw err
    }
}

/**
 * Create a pull request that contains the generated patch in the
 * description. This function does not apply the diff automatically.
 *
 * @param {number|string} issueNumber
 * @param {string} patch - unified diff text produced by the AI
 * @returns {object} pull request data from GitHub
 */
async function createPullRequest(issueNumber, patch) {
    const headers = {
        Authorization: `Bearer ${GITHUB_TOKEN}`,
        Accept: "application/vnd.github+json"
    }

    const base = process.env.GITHUB_BASE_BRANCH || "main"
    const head = `ai-fix-${issueNumber}-${Date.now()}`

    const baseRefRes = await axios.get(
        `https://api.github.com/repos/${OWNER}/${REPO}/git/ref/heads/${base}`,
        { headers }
    )
    const sha = baseRefRes.data.object.sha

    await axios.post(
        `https://api.github.com/repos/${OWNER}/${REPO}/git/refs`,
        { ref: `refs/heads/${head}`, sha },
        { headers }
    )

    const title = `Fix for issue #${issueNumber}`
    const body = `This pull request was generated by the AI helper.

Patch:

\`\`\`diff
${patch}
\`\`\``

    const prRes = await axios.post(
        `https://api.github.com/repos/${OWNER}/${REPO}/pulls`,
        { title, head, base, body },
        { headers }
    )

    return prRes.data
}

module.exports = { getIssue, createPullRequest }
